import type {
  ExtensionAPI,
  AgentToolUpdateCallback,
  ExtensionContext,
} from "@mariozechner/pi-coding-agent";
import { Type, type Static } from "@sinclair/typebox";
import { textResult, errorResult } from "../../shared/tool-utils";
import { throttledFetch } from "../../shared/throttle";

const MCP_ENDPOINT = "https://mcp.deepwiki.com/mcp";

const HEADERS = {
  "Content-Type": "application/json",
  Accept: "application/json, text/event-stream",
};

interface McpResponse<T = unknown> {
  jsonrpc: string;
  id: number;
  result?: T;
  error?: { code: number; message: string };
}

interface ToolCallResult {
  content: { type: string; text: string }[];
}

let requestId = 0;

async function callMcpTool(
  name: string,
  args: Record<string, unknown>,
  signal?: AbortSignal,
): Promise<string> {
  const response = await throttledFetch(MCP_ENDPOINT, {
    method: "POST",
    headers: HEADERS,
    body: JSON.stringify({
      jsonrpc: "2.0",
      id: ++requestId,
      method: "tools/call",
      params: { name, arguments: args },
    }),
    signal,
  });

  if (!response.ok) {
    throw new Error(
      `MCP request failed: ${response.status} ${response.statusText}`,
    );
  }

  const text = await response.text();

  // Parse SSE response
  const dataMatch = /^data:\s*(.+)$/m.exec(text);
  if (!dataMatch) {
    throw new Error("Invalid MCP response format");
  }

  const data = JSON.parse(dataMatch[1]) as McpResponse<ToolCallResult>;

  if (data.error) {
    throw new Error(`MCP error: ${data.error.message}`);
  }

  if (!data.result?.content?.[0]?.text) {
    throw new Error("Empty response from DeepWiki");
  }

  return data.result.content[0].text;
}

// Parameter schemas
const RepoNameParams = Type.Object({
  repoName: Type.String({
    description:
      'GitHub repository in owner/repo format (e.g. "facebook/react")',
  }),
});

const AskQuestionParams = Type.Object({
  repoName: Type.Union([
    Type.String({
      description:
        'GitHub repository in owner/repo format (e.g. "facebook/react")',
    }),
    Type.Array(Type.String(), {
      description: "List of repositories (max 10)",
    }),
  ]),
  question: Type.String({
    description: "The question to ask about the repository",
  }),
});

type RepoNameParamsType = Static<typeof RepoNameParams>;
type AskQuestionParamsType = Static<typeof AskQuestionParams>;

export default function deepwikiExtension(pi: ExtensionAPI) {
  pi.registerTool({
    name: "deepwiki-read-structure",
    label: "DeepWiki Structure",
    description: `Get a list of documentation topics for a GitHub repository.

Use this to:
- Discover what documentation is available for a repo
- Get an overview of the repository structure
- Find specific documentation topics

Returns a list of documentation topics and sections.`,
    parameters: RepoNameParams,

    async execute(
      _toolCallId: string,
      params: RepoNameParamsType,
      signal: AbortSignal | undefined,
      _onUpdate: AgentToolUpdateCallback | undefined,
      _ctx: ExtensionContext,
    ) {
      try {
        const result = await callMcpTool(
          "read_wiki_structure",
          { repoName: params.repoName },
          signal,
        );
        return textResult(result, { repoName: params.repoName });
      } catch (error) {
        return errorResult(error, { repoName: params.repoName });
      }
    },
  });

  pi.registerTool({
    name: "deepwiki-read-contents",
    label: "DeepWiki Contents",
    description: `View full documentation about a GitHub repository.

Use this to:
- Read the complete documentation for a repo
- Understand how a project works
- Get detailed explanations of architecture and code

Returns comprehensive documentation generated by AI.`,
    parameters: RepoNameParams,

    async execute(
      _toolCallId: string,
      params: RepoNameParamsType,
      signal: AbortSignal | undefined,
      _onUpdate: AgentToolUpdateCallback | undefined,
      _ctx: ExtensionContext,
    ) {
      try {
        const result = await callMcpTool(
          "read_wiki_contents",
          { repoName: params.repoName },
          signal,
        );
        return textResult(result, { repoName: params.repoName });
      } catch (error) {
        return errorResult(error, { repoName: params.repoName });
      }
    },
  });

  pi.registerTool({
    name: "deepwiki-ask",
    label: "DeepWiki Ask",
    description: `Ask any question about a GitHub repository and get an AI-powered, context-grounded response.

Use this to:
- Ask specific questions about how code works
- Get explanations of functions, classes, or modules
- Understand design decisions and patterns
- Compare multiple repositories (max 10)

Returns an AI-generated answer based on the repository's code and documentation.`,
    parameters: AskQuestionParams,

    async execute(
      _toolCallId: string,
      params: AskQuestionParamsType,
      signal: AbortSignal | undefined,
      _onUpdate: AgentToolUpdateCallback | undefined,
      _ctx: ExtensionContext,
    ) {
      try {
        const result = await callMcpTool(
          "ask_question",
          { repoName: params.repoName, question: params.question },
          signal,
        );
        return textResult(result, {
          repoName: params.repoName,
          question: params.question,
        });
      } catch (error) {
        return errorResult(error, {
          repoName: params.repoName,
          question: params.question,
        });
      }
    },
  });
}
